export const TODO_ADD_LOADING = 'TODO_ADD_LOADING'
export const TODO_ADD_ERROR = 'TODO_ADD_ERROR'

export const TODO_FETCH_LOADING = 'TODO_FETCH_LOADING'
export const TODO_FETCH_ERROR = 'TODO_FETCH_ERROR'
export const TODO_FETCH_SUCCESS = 'TODO_FETCH_SUCCESS'

export const TODO_SORT = 'TODO_SORT'
export const TODO_PAGE = 'TODO_PAGE'

export const ADMIN_LOGIN = 'ADMIN_LOGIN'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'


export const TODO_EDIT_LOADING = 'TODO_EDIT_LOADING'
export const TODO_EDIT_ERROR = 'TODO_EDIT_ERROR'
export const TODO_EDIT_SUCCESS = 'TODO_EDIT_SUCCESS'
